import { NextResponse } from "next/server";
import { stripe } from "@/lib/stripe";
import { createClient } from "@supabase/supabase-js";
import QRCode from "qrcode";
import nodemailer from "nodemailer";

const endpointSecret = process.env.STRIPE_WEBHOOK_SECRET!;

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_PASS,
  },
});

export async function POST(req: Request) {
  // 1. Get the Raw Body
  // In Express: request.body (configured via express.raw() middleware)
  // In Next.js: We must read the text stream manually.
  const body = await req.text();

  // 2. Get the Signature
  const sig = req.headers.get("stripe-signature") as string;

  let event;

  // 3. Verify the Event (Exact match to Docs)
  try {
    event = stripe.webhooks.constructEvent(body, sig, endpointSecret);
  } catch (err: any) {
    // In Express: response.status(400).send(`Webhook Error: ${err.message}`);
    return NextResponse.json(
      { error: `Webhook Error: ${err.message}` },
      { status: 400 }
    );
  }

  // 4. Handle the Event
  switch (event.type) {
    case "checkout.session.completed":
      const session = event.data.object;
      console.log(session)

      await fulfillOrder(session);

      break;
    default:
      console.log(`Unhandled event type ${event.type}`);
  }

  // 5. Return Success
  // In Express: response.send();
  return NextResponse.json({ received: true });
}

async function fulfillOrder(session: any) {
  const { userId } = session.metadata;
  const userEmail = session.customer_details?.email;

  console.log(`💰 Payment received! Session ID: ${session.id}`);

  // Initialize Admin Client (Bypasses RLS)
  const supabaseAdmin = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  // 1. insert and return ticket data
  const { data: ticketData, error } = await supabaseAdmin
    .from("tickets")
    .insert({
      user_id: userId,
      stripe_session_id: session.id,
      amount_paid: session.amount_total / 100,
      status: "valid",
    })
    .select()
    .single();

  if (error) {
    console.error("Supabase Error: ", error);
  } else {
    console.log("✅ Ticket saved to database");
  }

  // 2. get uuid generated by db to create QR code
  const qrCodeUrl = await QRCode.toDataURL(ticketData.ticket_code);

  // 3. send email with QR code
  if (userEmail) {
    try {
      await transporter.sendMail({
        from: '"Golden Tikkee" <' + process.env.GMAIL_USER + ">",
        to: userEmail,
        subject: "Your Golden Ticket",
        html: `
          <div style="font-family: sans-serif; text-align: center; padding: 20px;">
            <h1>You're going to the event!</h1>
            <p>Thank you for your purchase. Here is your unique entry code.</p>
            
            <img src="cid:unique-qr-code" alt="Ticket QR" width="200" style="margin: 20px auto; display: block;" />
            
            <p style="color: #888; font-size: 12px;">Code: ${ticketData.ticket_code}</p>

            <footer>If you did not make this purchase, or if the QR code is not working, please contact our support team immediately.</footer>
          </div>
        `,
        attachments: [
          {
            filename: "golden-tikkee-qr-ticket.png",
            path: qrCodeUrl, // Nodemailer handles the data url automatically
            cid: "unique-qr-code", // reference the image src in the HTML above
          },
        ],
      });
      console.log(`📧 Email sent to ${userEmail}`);
    } catch (emailError) {
      console.error("Email failed: ", emailError);
    }
  }
}
